import {
  Image,
  Text,
  View,
  StyleSheet,
  Pressable,
  ActivityIndicator,
  ScrollView,
  Modal,
} from "react-native";
import { Ionicons } from "@expo/vector-icons";
import Logo from "../../auth/Assets/Logo.svg";
import { useEffect, useRef, useState, useCallback } from "react";
import api from "../../../services/api";
import { useAuth } from "../../../context/AuthContext";
import { useNavigation } from "@react-navigation/native";
import type { NativeStackNavigationProp } from "@react-navigation/native-stack";

const DAY_NAMES = [
  "Domingo",
  "Segunda-feira",
  "Terça-feira",
  "Quarta-feira",
  "Quinta-feira",
  "Sexta-feira",
  "Sábado",
];

interface Schedule {
  id: string;
  dayOfWeek: number;
  startTime: string;
  endTime: string;
  room: { name: string };
  courseName: string;
}

type QRStatus = "idle" | "loading" | "active" | "expired";

interface QRData {
  qrImage: string;
  expiresAt: string;
  schedule: {
    course: string;
    room: string;
    startTime: string;
    endTime: string;
  };
}

type RootStackParamList = {
  Login: undefined;
  Student: undefined;
  Management: undefined;
};

export default function Home() {
  const [studentName, setStudentName] = useState("Aluno");
  const [schedules, setSchedules] = useState<Schedule[]>([]);
  const [profileLoading, setProfileLoading] = useState(true);

  const [qr, setQr] = useState<QRData | null>(null);
  const [qrStatus, setQrStatus] = useState<QRStatus>("idle");
  const [secondsLeft, setSecondsLeft] = useState(0);
  const [qrModalVisible, setQrModalVisible] = useState(false);

  const { signOut } = useAuth();

  const navigation =
    useNavigation<NativeStackNavigationProp<RootStackParamList>>();

  const timerRef = useRef<ReturnType<typeof setInterval> | null>(null);
  const autoGeneratedRef = useRef(false);
  const qrStatusRef = useRef<QRStatus>("idle");

  const todayIndex = new Date().getDay();
  const todaySchedules = schedules.filter((s) => s.dayOfWeek === todayIndex);

  const nextSchedule = todaySchedules[0] ?? schedules[0] ?? null;

  useEffect(() => {
    api
      .get("/api/students/me")
      .then(({ data }) => {
        setStudentName(data.name);
        const flat: Schedule[] = [];
        for (const enr of data.courses) {
          for (const sch of enr.course.schedules) {
            flat.push({ ...sch, courseName: enr.course.name });
          }
        }
        setSchedules(flat);
      })
      .catch(() => {})
      .finally(() => setProfileLoading(false));
  }, []);

  const setStatus = useCallback((s: QRStatus) => {
    qrStatusRef.current = s;
    setQrStatus(s);
  }, []);

  const startCountdown = useCallback((expiresAt: string) => {
    if (timerRef.current) clearInterval(timerRef.current);

    const totalSecs = Math.max(
      0,
      Math.floor((new Date(expiresAt).getTime() - Date.now()) / 1000),
    );

    setSecondsLeft(totalSecs);

    if (totalSecs <= 0) return;

    timerRef.current = setInterval(() => {
      setSecondsLeft((prev) => {
        if (prev <= 1) {
          clearInterval(timerRef.current!);
          timerRef.current = null;
          return 0;
        }
        return prev - 1;
      });
    }, 1000);
  }, []);

  useEffect(() => {
    if (secondsLeft === 0 && qrStatusRef.current === "active") {
      setStatus("expired");
      setQr(null);
    }
  }, [secondsLeft, setStatus]);

  useEffect(() => {
    return () => {
      if (timerRef.current) clearInterval(timerRef.current);
    };
  }, []);

  const generateQR = useCallback(
    async (scheduleId: string) => {
      if (qrStatusRef.current === "loading") return;
      setStatus("loading");
      try {
        const { data } = await api.post<QRData>("/api/qrcode/generate", {
          scheduleId,
        });
        setQr(data);
        setStatus("active");
        startCountdown(data.expiresAt);
      } catch (err: any) {
        const msg =
          err?.response?.data?.error ?? "Não foi possível gerar o QR Code.";
        console.warn("[QR] Erro ao gerar:", msg);
        setStatus("idle");
      }
    },
    [setStatus, startCountdown],
  );

  useEffect(() => {
    if (profileLoading) return;
    if (autoGeneratedRef.current) return;
    if (!nextSchedule) return;

    autoGeneratedRef.current = true;
    generateQR(nextSchedule.id);
  }, [profileLoading, nextSchedule, generateQR]);

  const pad = (n: number) => String(n).padStart(2, "0");
  const timerLabel = `${pad(Math.floor(secondsLeft / 60))}:${pad(secondsLeft % 60)}`;

  const buttonDisabled =
    qrStatus === "loading" || qrStatus === "active" || !nextSchedule;

  const buttonLabel =
    qrStatus === "loading"
      ? "GERANDO..."
      : qrStatus === "active"
        ? "QR CODE ATIVO"
        : "GERAR NOVO QR CODE";

  async function handleLogout() {
    await signOut();

    navigation.reset({
      index: 0,
      routes: [{ name: "Login" }],
    });
  }

  return (
    <ScrollView
      style={styles.scrollRoot}
      contentContainerStyle={styles.scrollContent}
      showsVerticalScrollIndicator={false}
    >
      <Image
        source={require("../../auth/Assets/SenacBackground.png")}
        style={styles.image}
      />
      <View style={styles.header}>
        <View style={styles.topRow}>
          <View style={styles.welcomeContainer}>
            <Text style={styles.title}>Olá, {studentName}!</Text>
            <Text style={styles.subtitle}>Bem-vindo(a) de volta.</Text>
          </View>

          <Pressable style={styles.logoutButton} onPress={handleLogout}>
            <Ionicons name="log-out-outline" size={22} color="#FFFFFF" />
          </Pressable>
        </View>

        <Logo
          width={160}
          height={80}
          style={{ marginTop: 5, marginBottom: 5 }}
        />
      </View>
      <View style={styles.card}>
        <Text style={styles.titleCard}>ACESSO RÁPIDO</Text>
        <Text style={styles.qrTitle}>Seu QR Code de acesso</Text>

        <View style={styles.qrContent}>
          <View style={styles.qrImageWrapper}>
            {qrStatus === "loading" ? (
              <ActivityIndicator color="#2F6BFF" size="large" />
            ) : qr?.qrImage && qrStatus === "active" ? (
              <Pressable onPress={() => setQrModalVisible(true)}>
                <Image source={{ uri: qr.qrImage }} style={styles.qrImage} />
              </Pressable>
            ) : (
              <View style={styles.qrPlaceholder}>
                <Ionicons
                  name={
                    qrStatus === "expired"
                      ? "close-circle-outline"
                      : "qr-code-outline"
                  }
                  size={52}
                  color={qrStatus === "expired" ? "#FF4C4C" : "#2F6BFF"}
                />
                <Text
                  style={[
                    styles.placeholderLabel,
                    qrStatus === "expired" && { color: "#FF4C4C" },
                  ]}
                >
                  {qrStatus === "expired" ? "Expirado" : "Carregando..."}
                </Text>
              </View>
            )}
          </View>
          <View style={styles.qrInfo}>
            {qr?.schedule && qrStatus === "active" ? (
              <>
                <Text style={styles.scheduleLabel}>{qr.schedule.course}</Text>
                <Text style={styles.scheduleRoom}>{qr.schedule.room}</Text>
                <Text style={styles.scheduleTime}>
                  {qr.schedule.startTime} – {qr.schedule.endTime}
                </Text>
              </>
            ) : (
              <Text style={styles.description}>
                {qrStatus === "expired"
                  ? "Seu QR Code expirou.\nGere um novo para continuar."
                  : "Apresente este código no leitor da portaria para liberar seu acesso."}
              </Text>
            )}
            {qrStatus === "active" && secondsLeft > 0 && (
              <View style={styles.timerBlock}>
                <Text style={styles.expireLabel}>Expira em</Text>
                <Text
                  style={[
                    styles.timer,
                    secondsLeft < 60 && { color: "#FF4C4C" },
                  ]}
                >
                  {timerLabel}
                </Text>
              </View>
            )}
          </View>
        </View>
        {qrStatus === "active" && secondsLeft > 0 && (
          <View style={styles.progressBar}>
            <View
              style={[
                styles.progressFill,
                {
                  width: `${Math.min(100, (secondsLeft / 300) * 100)}%`,
                  backgroundColor: secondsLeft < 60 ? "#FF4C4C" : "#2F6BFF",
                },
              ]}
            />
          </View>
        )}
        <Pressable
          style={[styles.button, buttonDisabled && styles.buttonDisabled]}
          onPress={() => nextSchedule && generateQR(nextSchedule.id)}
          disabled={buttonDisabled}
        >
          {qrStatus === "loading" ? (
            <ActivityIndicator color="#FFFFFF" size="small" />
          ) : (
            <Ionicons name="qr-code-outline" size={20} color="#FFFFFF" />
          )}
          <Text style={styles.buttonText}>{buttonLabel}</Text>
        </Pressable>
      </View>
      <View style={styles.cardTwo}>
        <Text style={styles.titleCard}>HOJE — {DAY_NAMES[todayIndex]}</Text>
        {nextSchedule ? (
          <View style={styles.scheduleCard}>
            <View style={styles.scheduleIconBox}>
              <Ionicons name="calendar-outline" size={24} color="#FFFFFF" />
            </View>
            <View style={styles.scheduleDetails}>
              <Text style={styles.nextClassLabel}>Próxima aula</Text>
              <Text style={styles.className}>{nextSchedule.courseName}</Text>
              <Text style={styles.classTime}>
                {nextSchedule.startTime} - {nextSchedule.endTime}
              </Text>
              <Text style={styles.classRoom}>{nextSchedule.room.name}</Text>
            </View>
          </View>
        ) : (
          <Text style={styles.noClassText}>Nenhuma aula hoje.</Text>
        )}
      </View>

      <Modal visible={qrModalVisible} transparent animationType="fade">
        <Pressable
          style={styles.qrModalOverlay}
          onPress={() => setQrModalVisible(false)}
        >
          {qr?.qrImage && (
            <Image source={{ uri: qr.qrImage }} style={styles.qrModalImage} />
          )}
        </Pressable>
      </Modal>
    </ScrollView>
  );
}

const styles = StyleSheet.create({
  scrollRoot: { flex: 1, backgroundColor: "#021127" },
  scrollContent: { alignItems: "center", paddingBottom: 32 },
  image: { width: "100%", height: 250 },
  header: {
    width: "92%",
    marginTop: -200,
    marginBottom: 8,
  },
  title: { color: "#FFF", fontSize: 26, fontWeight: "bold" },
  subtitle: { color: "#C8D2E3", fontSize: 13, marginTop: 2 },
  card: {
    backgroundColor: "#051e3e",
    width: "92%",
    marginTop: 12,
    borderRadius: 14,
    borderWidth: 1,
    borderColor: "#0B3D91",
    padding: 16,
  },
  titleCard: {
    color: "#80B3F8",
    fontWeight: "bold",
    fontSize: 13,
    letterSpacing: 1,
  },
  qrTitle: { color: "#FFFFFF", fontWeight: "bold", fontSize: 14, marginTop: 8 },
  qrContent: {
    flexDirection: "row",
    alignItems: "center",
    marginTop: 16,
    gap: 16,
  },

  qrImageWrapper: {
    width: 140,
    height: 140,
    borderRadius: 12,
    backgroundColor: "#0F213F",
    alignItems: "center",
    justifyContent: "center",
    overflow: "hidden",
  },
  qrImage: { width: 140, height: 140 },
  qrPlaceholder: { alignItems: "center", gap: 6 },
  placeholderLabel: { color: "#2F6BFF", fontSize: 12, fontWeight: "600" },

  qrInfo: { flex: 1, justifyContent: "center" },
  description: { color: "#C8D2E3", fontSize: 12, lineHeight: 18 },
  scheduleLabel: { color: "#FFFFFF", fontSize: 13, fontWeight: "bold" },
  scheduleRoom: { color: "#80B3F8", fontSize: 12, marginTop: 4 },
  scheduleTime: { color: "#C8D2E3", fontSize: 12, marginTop: 2 },

  timerBlock: { marginTop: 12 },
  expireLabel: { color: "#9CA8B8", fontSize: 11 },
  timer: { color: "#2F6BFF", fontSize: 36, fontWeight: "bold", lineHeight: 42 },

  progressBar: {
    height: 4,
    backgroundColor: "#112e61",
    borderRadius: 2,
    marginTop: 14,
    overflow: "hidden",
  },
  progressFill: {
    height: "100%",
    borderRadius: 2,
  },

  button: {
    backgroundColor: "#0B4BBB",
    height: 44,
    borderRadius: 8,
    marginTop: 14,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 10,
  },
  buttonDisabled: { backgroundColor: "#1a3057", opacity: 0.6 },
  buttonText: { color: "#FFFFFF", fontWeight: "bold", fontSize: 13 },

  cardTwo: {
    backgroundColor: "#051e3e",
    width: "92%",
    marginTop: 14,
    borderRadius: 14,
    borderWidth: 1,
    borderColor: "#0B3D91",
    padding: 16,
  },
  scheduleCard: {
    backgroundColor: "#112e61",
    borderRadius: 12,
    padding: 14,
    marginTop: 12,
    flexDirection: "row",
    alignItems: "flex-start",
  },
  scheduleIconBox: {
    width: 42,
    height: 42,
    borderRadius: 8,
    backgroundColor: "#0B4BBB",
    alignItems: "center",
    justifyContent: "center",
    marginRight: 14,
  },
  scheduleDetails: { flex: 1 },
  nextClassLabel: { color: "#80B3F8", fontSize: 13 },
  className: {
    color: "#FFFFFF",
    fontSize: 14,
    fontWeight: "bold",
    marginTop: 2,
  },
  classTime: { color: "#C8D2E3", fontSize: 13, marginTop: 6 },
  classRoom: { color: "#C8D2E3", fontSize: 12, marginTop: 2 },
  noClassText: { color: "#C8D2E3", marginTop: 10, fontSize: 13 },
  qrModalOverlay: {
    flex: 1,
    backgroundColor: "rgba(0,0,0,0.95)",
    alignItems: "center",
    justifyContent: "center",
    padding: 24,
  },

  qrModalImage: {
    width: "100%",
    aspectRatio: 1,
    resizeMode: "contain",
    backgroundColor: "#FFFFFF",
  },
  topRow: {
    flexDirection: "row",
    alignItems: "center",
  },

  logoutButton: {
    width: 42,
    height: 42,
    borderRadius: 21,
    backgroundColor: "rgba(255,255,255,0.12)",
    alignItems: "center",
    justifyContent: "center",
    marginRight: 12,
  },

  welcomeContainer: {
    flex: 1,
  },
});
